<?php

/**
 * Class CRM_Financeextras_Page_AllocatedPaymentsAngular.
 *
 * Define an Angular base-page for allocated payments reports.
 */
class CRM_Financeextras_Page_AllocatedPaymentsAngular extends \CRM_Core_Page {

  /**
   * Run Function.
   *
   * This function takes care of all the things common to all
   * pages. This typically involves assigning the appropriate
   * smarty variable :)
   *
   * @return string
   *   The content generated by running this page
   */
  public function run() {
    $loader = Civi::service('angularjs.loader');
    $loader->setPageName('civicrm/allocated-payments');
    $loader->addModules(['crmApp', 'allocated-payments']);
    \Civi::resources()->addSetting([
      'crmApp' => [
        'defaultRoute' => '/report',
      ],
    ]);

    return parent::run();
  }

  /**
   * Get Template File Name.
   *
   * @inheritdoc
   */
  public function getTemplateFileName() {
    return 'Civi/Angular/Page/Main.tpl';
  }

}
