<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from io.compuco.financeextras/xml/schema/CRM/Financeextras/Company.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:efebb3d413c6edf68d8f1d1ed8d39799)
 */
use CRM_Financeextras_ExtensionUtil as E;

/**
 * Database access object for the Company entity.
 */
class CRM_Financeextras_DAO_Company extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'financeextras_company';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique Company ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Contact
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * FK to the message template.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $invoice_template_id;

  /**
   * @var string|null
   *   (SQL type: varchar(11))
   *   Note that values will be retrieved from the database as a string.
   */
  public $invoice_prefix;

  /**
   * @var string|null
   *   (SQL type: varchar(11))
   *   Note that values will be retrieved from the database as a string.
   */
  public $next_invoice_number;

  /**
   * FK to the message template.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $creditnote_template_id;

  /**
   * @var string|null
   *   (SQL type: varchar(11))
   *   Note that values will be retrieved from the database as a string.
   */
  public $creditnote_prefix;

  /**
   * @var string|null
   *   (SQL type: varchar(11))
   *   Note that values will be retrieved from the database as a string.
   */
  public $next_creditnote_number;

  /**
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $receivable_payment_method;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'financeextras_company';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Companies') : E::ts('Company');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique Company ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_company.id',
          'table_name' => 'financeextras_company',
          'entity' => 'Company',
          'bao' => 'CRM_Financeextras_DAO_Company',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('FK to Contact'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_company.contact_id',
          'table_name' => 'financeextras_company',
          'entity' => 'Company',
          'bao' => 'CRM_Financeextras_DAO_Company',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'invoice_template_id' => [
          'name' => 'invoice_template_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Invoice Template ID'),
          'description' => E::ts('FK to the message template.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_company.invoice_template_id',
          'table_name' => 'financeextras_company',
          'entity' => 'Company',
          'bao' => 'CRM_Financeextras_DAO_Company',
          'localizable' => 0,
          'FKClassName' => 'CRM_Core_DAO_MessageTemplate',
          'html' => [
            'label' => E::ts("Invoice Template"),
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_msg_template',
            'keyColumn' => 'id',
            'labelColumn' => 'msg_title',
          ],
          'add' => NULL,
        ],
        'invoice_prefix' => [
          'name' => 'invoice_prefix',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Invoice Prefix'),
          'maxlength' => 11,
          'size' => CRM_Utils_Type::TWELVE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_company.invoice_prefix',
          'table_name' => 'financeextras_company',
          'entity' => 'Company',
          'bao' => 'CRM_Financeextras_DAO_Company',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'next_invoice_number' => [
          'name' => 'next_invoice_number',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Next Invoice Number'),
          'maxlength' => 11,
          'size' => CRM_Utils_Type::TWELVE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_company.next_invoice_number',
          'table_name' => 'financeextras_company',
          'entity' => 'Company',
          'bao' => 'CRM_Financeextras_DAO_Company',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'creditnote_template_id' => [
          'name' => 'creditnote_template_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Credit Note Template ID'),
          'description' => E::ts('FK to the message template.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_company.creditnote_template_id',
          'table_name' => 'financeextras_company',
          'entity' => 'Company',
          'bao' => 'CRM_Financeextras_DAO_Company',
          'localizable' => 0,
          'FKClassName' => 'CRM_Core_DAO_MessageTemplate',
          'html' => [
            'label' => E::ts("Credit Note Template"),
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_msg_template',
            'keyColumn' => 'id',
            'labelColumn' => 'msg_title',
          ],
          'add' => NULL,
        ],
        'creditnote_prefix' => [
          'name' => 'creditnote_prefix',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Credit Note Prefix'),
          'maxlength' => 11,
          'size' => CRM_Utils_Type::TWELVE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_company.creditnote_prefix',
          'table_name' => 'financeextras_company',
          'entity' => 'Company',
          'bao' => 'CRM_Financeextras_DAO_Company',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'next_creditnote_number' => [
          'name' => 'next_creditnote_number',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Next Credit Note Number'),
          'maxlength' => 11,
          'size' => CRM_Utils_Type::TWELVE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_company.next_creditnote_number',
          'table_name' => 'financeextras_company',
          'entity' => 'Company',
          'bao' => 'CRM_Financeextras_DAO_Company',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'receivable_payment_method' => [
          'name' => 'receivable_payment_method',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Accounts Receivable Payment Method'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_company.receivable_payment_method',
          'table_name' => 'financeextras_company',
          'entity' => 'Company',
          'bao' => 'CRM_Financeextras_DAO_Company',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Accounts Receivable Payment Method"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'xtras_company', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'xtras_company', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
