<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from io.compuco.financeextras/xml/schema/CRM/Financeextras/CreditNoteAllocation.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:e1e524b1b5b8179627419e1e22e0f35b)
 */
use CRM_Financeextras_ExtensionUtil as E;

/**
 * Database access object for the CreditNoteAllocation entity.
 */
class CRM_Financeextras_DAO_CreditNoteAllocation extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'financeextras_credit_note_allocation';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique CreditNoteAllocation ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to CreditNote
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $credit_note_id;

  /**
   * FK to Contribution
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contribution_id;

  /**
   * One of the values of the financeextras_credit_note_allocation_type option group
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $type_id;

  /**
   * 3 character string, value from config setting or input via user.
   *
   * @var string|null
   *   (SQL type: varchar(3))
   *   Note that values will be retrieved from the database as a string.
   */
  public $currency;

  /**
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $reference;

  /**
   * Ammount allocated
   *
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $amount;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'financeextras_credit_note_allocation';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Credit Note Allocations') : E::ts('Credit Note Allocation');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'credit_note_id', 'financeextras_credit_note', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contribution_id', 'civicrm_contribution', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique CreditNoteAllocation ID'),
          'required' => TRUE,
          'where' => 'financeextras_credit_note_allocation.id',
          'table_name' => 'financeextras_credit_note_allocation',
          'entity' => 'CreditNoteAllocation',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteAllocation',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'credit_note_id' => [
          'name' => 'credit_note_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to CreditNote'),
          'where' => 'financeextras_credit_note_allocation.credit_note_id',
          'table_name' => 'financeextras_credit_note_allocation',
          'entity' => 'CreditNoteAllocation',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteAllocation',
          'localizable' => 0,
          'FKClassName' => 'CRM_Financeextras_DAO_CreditNote',
          'html' => [
            'type' => 'EntityRef',
          ],
          'add' => NULL,
        ],
        'contribution_id' => [
          'name' => 'contribution_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Contribution'),
          'where' => 'financeextras_credit_note_allocation.contribution_id',
          'table_name' => 'financeextras_credit_note_allocation',
          'entity' => 'CreditNoteAllocation',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteAllocation',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contribute_DAO_Contribution',
          'add' => NULL,
        ],
        'type_id' => [
          'name' => 'type_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('One of the values of the financeextras_credit_note_allocation_type option group'),
          'required' => FALSE,
          'where' => 'financeextras_credit_note_allocation.type_id',
          'default' => NULL,
          'table_name' => 'financeextras_credit_note_allocation',
          'entity' => 'CreditNoteAllocation',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteAllocation',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Type"),
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'financeextras_credit_note_allocation_type',
            'optionEditPath' => 'civicrm/admin/options/financeextras_credit_note_allocation_type',
          ],
          'add' => NULL,
        ],
        'currency' => [
          'name' => 'currency',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Financial Currency'),
          'description' => E::ts('3 character string, value from config setting or input via user.'),
          'maxlength' => 3,
          'size' => CRM_Utils_Type::FOUR,
          'where' => 'financeextras_credit_note_allocation.currency',
          'headerPattern' => '/cur(rency)?/i',
          'dataPattern' => '/^[A-Z]{3}$/',
          'default' => NULL,
          'table_name' => 'financeextras_credit_note_allocation',
          'entity' => 'CreditNoteAllocation',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteAllocation',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_currency',
            'keyColumn' => 'name',
            'labelColumn' => 'full_name',
            'nameColumn' => 'name',
            'abbrColumn' => 'symbol',
          ],
          'add' => NULL,
        ],
        'reference' => [
          'name' => 'reference',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Allocation Reference'),
          'where' => 'financeextras_credit_note_allocation.reference',
          'table_name' => 'financeextras_credit_note_allocation',
          'entity' => 'CreditNoteAllocation',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteAllocation',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
            'label' => E::ts("Reference"),
          ],
          'add' => NULL,
        ],
        'amount' => [
          'name' => 'amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Amount'),
          'description' => E::ts('Ammount allocated'),
          'required' => FALSE,
          'precision' => [
            20,
            2,
          ],
          'where' => 'financeextras_credit_note_allocation.amount',
          'table_name' => 'financeextras_credit_note_allocation',
          'entity' => 'CreditNoteAllocation',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteAllocation',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'xtras_credit_note_allocation', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'xtras_credit_note_allocation', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
