<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from io.compuco.financeextras/xml/schema/CRM/Financeextras/CreditNoteLine.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:01d680a6984ee40b3e467de6529744a2)
 */
use CRM_Financeextras_ExtensionUtil as E;

/**
 * Database access object for the CreditNoteLine entity.
 */
class CRM_Financeextras_DAO_CreditNoteLine extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'financeextras_credit_note_line';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique CreditNoteLine ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to CreditNote
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $credit_note_id;

  /**
   * FK to CiviCRM Financial Type
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $financial_type_id;

  /**
   * line item description
   *
   * @var string
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $description;

  /**
   * Quantity
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $quantity;

  /**
   * Unit Price
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $unit_price;

  /**
   * Tax amount for the line item
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $tax_amount;

  /**
   * Line Total
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $line_total;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'financeextras_credit_note_line';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Credit Note Lines') : E::ts('Credit Note Line');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique CreditNoteLine ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_credit_note_line.id',
          'table_name' => 'financeextras_credit_note_line',
          'entity' => 'CreditNoteLine',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteLine',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'credit_note_id' => [
          'name' => 'credit_note_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Credit Note ID'),
          'description' => E::ts('FK to CreditNote'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_credit_note_line.credit_note_id',
          'table_name' => 'financeextras_credit_note_line',
          'entity' => 'CreditNoteLine',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteLine',
          'localizable' => 0,
          'FKClassName' => 'CRM_Financeextras_DAO_CreditNote',
          'html' => [
            'type' => 'EntityRef',
          ],
          'add' => NULL,
        ],
        'financial_type_id' => [
          'name' => 'financial_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Financial Type ID'),
          'description' => E::ts('FK to CiviCRM Financial Type'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_credit_note_line.financial_type_id',
          'table_name' => 'financeextras_credit_note_line',
          'entity' => 'CreditNoteLine',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteLine',
          'localizable' => 0,
          'FKClassName' => 'CRM_Financial_DAO_FinancialType',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Financial Type"),
          ],
          'add' => NULL,
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Description'),
          'description' => E::ts('line item description'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_credit_note_line.description',
          'table_name' => 'financeextras_credit_note_line',
          'entity' => 'CreditNoteLine',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteLine',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
            'label' => E::ts("Item Description"),
          ],
          'add' => NULL,
        ],
        'quantity' => [
          'name' => 'quantity',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Quantity'),
          'description' => E::ts('Quantity'),
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_credit_note_line.quantity',
          'table_name' => 'financeextras_credit_note_line',
          'entity' => 'CreditNoteLine',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteLine',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Quantity"),
          ],
          'add' => NULL,
        ],
        'unit_price' => [
          'name' => 'unit_price',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Unit Price'),
          'description' => E::ts('Unit Price'),
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_credit_note_line.unit_price',
          'table_name' => 'financeextras_credit_note_line',
          'entity' => 'CreditNoteLine',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteLine',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Unit Price"),
          ],
          'add' => NULL,
        ],
        'tax_amount' => [
          'name' => 'tax_amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Tax Amount'),
          'description' => E::ts('Tax amount for the line item'),
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_credit_note_line.tax_amount',
          'table_name' => 'financeextras_credit_note_line',
          'entity' => 'CreditNoteLine',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteLine',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Tax"),
          ],
          'add' => NULL,
        ],
        'line_total' => [
          'name' => 'line_total',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Line Total'),
          'description' => E::ts('Line Total'),
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'financeextras_credit_note_line.line_total',
          'table_name' => 'financeextras_credit_note_line',
          'entity' => 'CreditNoteLine',
          'bao' => 'CRM_Financeextras_DAO_CreditNoteLine',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Line Total"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'xtras_credit_note_line', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'xtras_credit_note_line', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
